# Generated by Django 2.0 on 2018-01-03 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('artest', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('path', models.ImageField(blank=True, null=True, upload_to='artwork', verbose_name='artwork_file')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='dp', verbose_name='dp_file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
