# Generated by Django 2.0 on 2018-01-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180104_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='artwork', verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp', verbose_name='dp'),
        ),
    ]
