# Generated by Django 2.0 on 2018-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180104_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timestamp',
            field=models.DateTimeField(max_length=255),
        ),
    ]
