# Generated by Django 2.0 on 2018-01-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180104_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pub_key',
            new_name='private_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
