# Generated by Django 2.0 on 2018-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_artwork_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
