# Generated by Django 2.0 on 2018-01-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_artwork_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artest',
            new_name='artist',
        ),
    ]
